### ISSUE TITLE
Unexpected source state when querying: 2

### ISSUE THREAD

**Issue by sidsethupathi** [safety-data/akka-persistence-redis#10]
I've seen this error appear transiently in my logs when using `eventsByPersistenceId`:

```
Unexpected source state when querying: 2
```

I think it tracks down to https://github.com/safety-data/akka-persistence-redis/blob/17563b5f236ee88e57b8cc70b896270fa538c044/src/main/scala/akka/persistence/query/journal/redis/EventsByPersistenceIdSource.scala#L203-L205

which seems like it can get hit by https://github.com/safety-data/akka-persistence-redis/blob/17563b5f236ee88e57b8cc70b896270fa538c044/src/main/scala/akka/persistence/query/journal/redis/EventsByPersistenceIdSource.scala#L105-L107

Am I following this code path correctly?

**Comment by satabin** [comment]
Hi,
you are right, the state should be set to `Idle` before calling `query`. I will fix it an publish a new snapshot version tomorrow.
Thanks for reporting.

**Comment by satabin** [comment]
I believe this is now fixed in the latest snapshot version. Can you confirm?
