### ISSUE TITLE
bump to  akkaVersion = "2.5.17" ?

### ISSUE THREAD

**Issue by gytisgreitai** [safety-data/akka-persistence-redis#23]
Would it be possible to release a new version with 2.5.17 akka ?

**Comment by satabin** [comment]
It should not be a big problem. Poke @urieli, can you do this?

**Comment by urieli** [comment]
Ok, will try to find time for this in the next few days.

**Comment by urieli** [comment]
Fixed by https://github.com/safety-data/akka-persistence-redis/pull/24
