### ISSUE TITLE
why is it always looking for localhost ?

### ISSUE THREAD

**Issue by sssahas** [safety-data/akka-persistence-redis#25]
Hi,

Below is my example config, I'm connecting to remote redis server. It successfully connects to remote server, regardless, its always looking for localhost:6379 too and erroring out "connection refused".. 

how can I solve this ?

Please point me to documentation, if any.

```
    akka-persistence-redis {
      redis {
        mode = simple
        host = blah.redislabs.com
        port = 13423
        password = blah
     }
     journal.redis = ${akka-persistence-redis.redis}
   }
```

**Comment by satabin** [comment]
Hi, in what file do you overwrite the default redis configuration? `reference.conf` or `application.conf`?

**Comment by sssahas** [comment]
Yes, application.conf

**Comment by satabin** [comment]
Can you then provide me with the stacktrace of the exception please?

**Comment by satabin** [comment]
Other questions:
 - Do you use the `snapshot` part?
 - Do you use the `read-journal` part?

**Comment by sssahas** [comment]
I use both journal and snapshot.
It connects to remote redis fine but doesn't stop there, continuously
trying to connect to local redis too and retrying every 2 seconds.

I'll get the stack later tonight.

**Comment by satabin** [comment]
You also need to override the snapshot redis part then, the same way you did for journal:

```scala
akka-persistence-redis.snapshot.redis = ${akka-persistence-redis.redis}
```

This is due to the way typesafe config merges objects (first all reference.conf files are merged, then application.conf, but refeerences are not updated).

**Comment by sssahas** [comment]
Ah. it worked. Thank you
